services:
  app:
    container_name: phinvads-app
    build:
      context: .
      dockerfile: ops/Dockerfile.local
    ports:
      - 4000:4000
      - 4090:4090
    environment:
      - HOST=0.0.0.0
      - DB_HOST=phinvads-db
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    container_name: phinvads-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./:/app
volumes:
  db-data: