services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: phinvads
      POSTGRES_PASSWORD: phinvads
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./:/app

volumes:
  db-data:
